<?php

/**
 * @file
 * Contains \Drupal\bigmenu\MenuSliceFormController.
 */

namespace Drupal\bigmenu;

class MenuSliceFormController extends MenuFormController {

  /**
   * @var \Drupal\menu_link\MenuLinkInterface
   */
  protected $menuLink;

  protected function prepareEntity() {
    $this->menuLink = $this->getRequest()->attributes->get('menu_link');
  }

  /**
    * Overrides Drupal\Core\Entity\EntityFormController::form().
    */
   public function form(array $form, array &$form_state) {
     $menu = $this->entity;

     // Add menu links administration form for existing menus.
     if (!$menu->isNew() || $menu->isLocked()) {
       // Form API supports constructing and validating self-contained sections
       // within forms, but does not allow to handle the form section's submission
       // equally separated yet. Therefore, we use a $form_state key to point to
       // the parents of the form section.
       // @see self::submitOverviewForm()
       $form_state['menu_overview_form_parents'] = array('links');
       $form['links'] = array();
       $form['links'] = $this->buildOverviewForm($form['links'], $form_state, 2);
     }

     return $form;
   }

  protected function buildOverviewForm(array &$form, array &$form_state, $depth = 1) {
    $this->buildOverviewFormStub($form, $form_state);

    $links = array();
    $query = $this->entityQueryFactory->get('menu_link')
      ->condition('menu_name', $this->entity->id())
      ->condition('p' . $this->menuLink->depth, $this->menuLink->id() , '=');
    for ($i = 1; $i <= MENU_MAX_DEPTH; $i++) {
      $query->sort('p' . $i, 'ASC');
    }
    $result = $query->execute();

    if (!empty($result)) {
      $links = $this->menuLinkStorage->loadMultiple($result);
    }

    $delta = max(count($links), 50);
    // We indicate that a menu administrator is running the menu access check.
    $this->getRequest()->attributes->set('_menu_admin', TRUE);
    $tree = $this->menuTree->buildTreeData($links);
    $this->getRequest()->attributes->set('_menu_admin', FALSE);

    $form = array_merge($form, $this->buildOverviewTreeForm($tree, $delta));
    $form['#empty_text'] = t('There are no menu links yet. <a href="@link">Add link</a>.', array('@link' => url('admin/structure/menu/manage/' . $this->entity->id() .'/add')));

    return $form;
  }

  protected function buildOverviewTreeForm($tree, $delta) {
    return parent::buildOverviewTreeForm($tree, $delta); // TODO: Change the autogenerated stub
  }

}
